[FLOC-17441] Fail fast
flocktory/kafka-consumer pull request #9
Opened 2020-10-16 10:29 UTC by oxgrouby

2020-10-16 14:16 UTC, dpavlov requested changes

2020-10-16 14:16 UTC, dpavlov commented on src/com/flocktory/kafka_consumer.clj
> +
В этом случае он падает после первой ошибки а нам нужен конфигурируемый бюджет ошибок Например пусть мы задали бюджет  = 3 тогда consumer перейдет в exit только после 3х ошибок подряд

2020-10-19 08:51 UTC, sherpc commented
@oxgrouby добавил вместо себя @abogoyavlensky 🏃‍♂️ =)

2020-10-19 08:52 UTC, oxgrouby commented
@sherpc ХитрО

2020-10-19 09:15 UTC, abogoyavlensky commented on src/com/flocktory/protocol/config.clj
> +   :fail-budget 3
Предлагаю добавить инфу о новых опциях и об особых условиях совместного использования `fail-loop?` / `fail-fast?` в docstring протокола `IOptionalConfig` и WIKI проекта: https://github.com/flocktory/kafka-consumer/wiki/Configuration#ioptionalconfig

2020-10-19 09:17 UTC, abogoyavlensky commented on src/com/flocktory/protocol/tracer.clj
> +
Тоже можно добавить в WIKI https://github.com/flocktory/kafka-consumer/wiki/Logs-and-metrics#logs-and-metrics

2020-10-19 09:22 UTC, abogoyavlensky approved these changes
Пара минорных комментов по поводу доки.

2020-10-20 14:11 UTC, merged